sudo: true
language: ruby
cache: bundler

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bzr
  - bzr whoami 'Test <test@test.net>'

matrix:
  include:
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

bundler_args: --jobs 7

script: bundle exec rake travis:ci
