sudo: true
language: ruby
cache: bundler

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bzr
  - bzr whoami 'Test <test@test.net>'

matrix:
  include:
    - rvm: 2.1.9
    - rvm: 2.2.5
    - rvm: 2.3.1
  allow_failures:
    - rvm: 2.3.1

bundler_args: --jobs 7

script: bundle exec rake travis:ci
